# This tells Nixpacks to detect this as a Node.js project
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build || echo 'No build script found'"]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"